context:
  version: "0.13.0"

package:
  name: handlr-regex
  version: ${{ version }}

source:
  url: https://github.com/Anomalocaridid/handlr-regex/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 963126a7aa8277b7cc7886c518528473ce5117a5999c949b809e14beffdbad0d

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_LTO: fat
      CARGO_PROFILE_RELEASE_STRIP: symbols
    interpreter: nu
    content:
      - let prefix = $env.LIBRARY_PREFIX? | default $env.PREFIX
      # build main app and generate license data
      - cargo auditable install --path=. --root=($prefix) --no-track --locked --bins
      - cargo-bundle-licenses --format=yaml --output=THIRDPARTY.yml
      # copy manpage
      - mkdir ($prefix)/share/man/man1
      - cp --recursive target/*/release/build/handlr-regex-*/out/manual/man1/* ($prefix)/share/man/man1/
      # generate shell completions
      - if: build_platform == host_platform
        then:
          - mkdir ($prefix)/share/bash-completion/completions ($prefix)/share/fish/vendor_completions.d ($prefix)/share/zsh/site-functions
          - let bin = ($prefix)/bin/handlr
          - COMPLETE=bash ^$bin completion bash | save ($prefix)/share/bash-completion/completions/handlr
          - COMPLETE=fish ^$bin completion fish | save ($prefix)/share/fish/vendor_completions.d/handlr.fish
          - COMPLETE=zsh  ^$bin completion zsh  | save ($prefix)/share/zsh/site-functions/_handlr
  skip:
    - osx
    - win

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-auditable
    - cargo-bundle-licenses
    - nushell

tests:
  - script:
      - handlr --help
      - handlr --version
  - package_contents:
      bin:
        - handlr
      files:
        - if: unix and build_platform == host_platform
          then:
            - share/man/man1/handlr*.1
            - share/bash-completion/completions/handlr
            - share/fish/vendor_completions.d/handlr.fish
            - share/zsh/site-functions/_handlr
      strict: true

about:
  summary: Modern CLI to set default file handlers by extension or MIME type
  description: |
    `handlr-regex` is a fork of the unmaintained [`handlr`](https://github.com/chmln/handlr) with additional support for
    regular expressions. It is a modern alternative to [`xdg-utils`](https://www.freedesktop.org/wiki/Software/xdg-utils/)
    that allows to set default file handlers by file extension or MIME type, to set arbitrary commands as handlers based
    on regular expressions, to open multiple files at once, and more.
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  homepage: https://github.com/Anomalocaridid/handlr-regex
  repository: https://github.com/Anomalocaridid/handlr-regex

extra:
  recipe-maintainers:
    - salim-b
